version: '2'
services:
    db:
        image: mysql
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: message
        volumes:
            - './.data/mysql:/var/lib/mysql'
    message_app:
        build: ./build
        ports:
            - 85:80
        volumes:
            - ./:/app
        links:
            - db
        depends_on:
            - db

